name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_NAME
          # changes all uppercase characters to lowercase:
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          echo "expected to be main: ${{ github.ref_name }}"
          
          # push into main branch is a release to latest
          if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF_NAME" == "main" ]]; then
            docker tag $IMAGE_NAME $IMAGE_ID:latest
            docker push $IMAGE_ID:latest
            echo "docker push $IMAGE_ID:latest"
          fi
          
          # each PR has a separate tag: pr-<number>
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            PR=pr-${{ github.event.pull_request.number }}
            docker tag $IMAGE_NAME $IMAGE_ID:$PR
            docker push $IMAGE_ID:$PR
            echo "docker push $IMAGE_ID:$PR"

            if [[ "${{ github.event.pull_request.milestone }}" != "null" ]]; then
              MILESTONE=milestone-${{ github.event.pull_request.milestone.number }}
              echo MILESTONE=$MILESTONE
              docker tag $IMAGE_NAME $IMAGE_ID:$MILESTONE
              docker push $IMAGE_ID:$MILESTONE
              echo "docker push $IMAGE_ID:$MILESTONE"
            fi
          fi
          
